version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pgsql_container
    environment:
      POSTGRES_USER: dmon
      POSTGRES_PASSWORD: A1mostdone
      POSTGRES_DB: dmondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: Migrator.Dockerfile
    container_name: migrator_container
    environment:
      - ConnectionStrings__DefaultConnection=User ID=dmon;Password=A1mostdone;Host=db;Port=5432;Database=dmondb;
    depends_on:
      - db
    restart: on-failure:3

  services:
    build:
      context: .
      dockerfile: Services.Dockerfile 
    container_name: auction_container
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=dmon;Password=A1mostdone;Host=db;Port=5432;Database=dmondb;
    depends_on:
      - db
      - migrator

volumes:
  pgdata:
