export const ERROR_CODE_MESSAGES = {
    InternalServerError: 'Внутренняя ошибка сервера',
    InvalidUserNameOrPassword: 'Неверное имя пользователя или пароль',
    NotFound: 'Не найдено',
    InvalidRole: 'Неверная роль',
    Forbidden: 'Запрещено',
    InvalidBid: 'Неверная ставка',
    AuctionAlreadyStarted: 'Аукцион уже начался',
    InvalidLaunchPeriod: 'Неверный период запуска',
    InvalidInitialPrice: 'Неверная начальная цена',
    CategoriesEmpty: 'Выберите от 1 до 10 категорий',
    TitleTooLong: 'Слишком длинное название. Максимальная длина: 70 символов',
    DescriptionTooLong: 'Слишком длинное описание. Максимальная длина: 2048 символов',
    BidCommentTooLong: 'Слишком длинный комментарий. Максимальная длина: 120 символов',
    FirstNameTooLong: 'Слишком длинное имя. Максимальная длина: 32 символа',
    LastNameTooLong: 'Слишком длинная фамилия. Максимальная длина: 32 символа',
    EducationTooLong: 'Слишком длинное образование. Максимальная длина: 32 символа',
    BiographyTooLong: 'Слишком длинная биография. Максимальная длина: 32 символа',
    InvalidEmail: 'Неверный email',
    DuplicateUserName: 'Пользователь с таким именем уже существует',
    PasswordConfirmationFailed: 'Пароли не совпадают',
    PasswordTooShort: 'Пароли должны содержать не менее 6 символов',
    PasswordRequiresNonAlphanumeric: 'Пароли должны содержать хотя бы один не алфавитно-цифровой символ',
    PasswordRequiresUpper: 'Пароли должны содержать хотя бы один не алфавитно-цифровой символ',
}