export const ERROR_CODE_MESSAGES = {
    InternalServerError: 'Internal server error',
    InvalidUserNameOrPassword: 'Invalid user name or password',
    NotFound: 'Not found',
    InvalidRole: 'Invalid role',
    Forbidden: 'Forbidden',
    InvalidBid: 'Invalid bid',
    AuctionAlreadyStarted: 'Auction has already started',
    InvalidLaunchPeriod: 'Invalid launch period',
    InvalidInitialPrice: 'Invalid initial price',
    CategoriesEmpty: 'Choose from 1 to 10 categories',
    TitleTooLong: 'Title too long. Maximum length: 70 chars',
    DescriptionTooLong: 'Description too long. Maximum length: 512 chars',
    BidCommentTooLong: 'Comment too long. Maximum length: 70 chars',
    FirstNameTooLong: 'First name too long. Maximum value: 32 chars',
    LastNameTooLong: 'Last name too long. Maximum value: 32 chars',
    EducationTooLong: 'Education too long. Maximum value: 32 chars',
    BiographyTooLong: 'Biography too long. Maximum value: 32 chars',
    DuplicateUserName: 'User with this name already exists',
    PasswordConfirmationFailed: 'Passwords do not match',
    PasswordTooShort: 'Passwords must be at least 6 characters',
    PasswordRequiresNonAlphanumeric: 'Passwords must have at least one non alphanumeric character',
    PasswordRequiresUpper: 'Passwords must have at least one non alphanumeric character',
}